### ISSUE TITLE
DarkMode again, fw 4.31.19086

### ISSUE THREAD

**Issue by jackiew1** [pgaskin/NickelMenu#120] opened 2022-01-21 16:44 UTC
@pgaskin , In case you haven't seen MR yet, the change you made to make DarkMode work (posted [here](https://www.mobileread.com/forums/showpost.php?p=4141992&postcount=555)) seems to have disappeared from NickelMenu v5.3

Edit: Sorry didn't see that you'd already commented on this yesterday in #116

**Comment by pgaskin** [comment] 2022-01-21 21:20
Yes, it's currently in the `elipsa` branch.

**Comment by pgaskin** [comment] 2022-01-21 21:20
duplicate of #116

**Closed by pgaskin** 2022-01-21 21:20 UTC

**Comment by jackiew1** [comment] 2022-01-21 21:38
> Yes, it's currently in the `elipsa` branch.

Sorry are you saying there's an existing version of `KoboRoot.tgz` where both DarkMode and the Highlighting issue in #119 are fixed?
